source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'chartkick', '~> 1.5', '>= 1.5.2'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'devise', '~> 4.1', '>= 4.1.1'
gem 'exception_notification', '~> 4.1.0'
gem 'cancancan', '~> 1.15'
gem 'exception_notification-rake', '~> 0.2.1'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'bootstrap', '~> 4.0.0.alpha5'
gem 'googlecharts'
gem 'puma'

group :development do
    # Access an IRB console on exception pages or by using <%= console %> in views
    gem 'faker'
    gem 'web-console', '~> 2.0'
    gem 'capistrano', '~> 3.5'
    gem 'capistrano-bundler', '~> 1.1', '>= 1.1.4'
    gem 'capistrano-rails', '~> 1.1', '>= 1.1.6'
    gem 'capistrano-rbenv', '~> 2.0', '>= 2.0.4'
    gem 'capistrano3-puma'
    gem 'capistrano-rails-console'
    gem 'spring'
end
