development:
 adapter: postgresql
 encoding: unicode
 database: echoworks_dev
 host: localhost
 pool: 5
 username: mahi
 password: mahi

production:
 adapter: postgresql
 encoding: unicode
 database: echoworks_prod
 host: localhost
 pool: 5
 username: mahi
 password: mahi
